console.log("Hello! I'm your coding fun fact guide!");
let botName="Chatbot";
let botLocation="Universe";
let favoriteLanguage="Javascript";
console.log("My name is (botName) and I live on (botLocation).");
console.log("My favorite programming language is (favoriteLanguage).");
let codingFact=favoriteLanguage+" is a frontend as well as backend language";
console.log(codingFact);
codingFact=favoriteLanguage+" is similar to python";
console.log(codingFact);
codingFact=favoriteLanguage+" is easy ";
console.log(codingFact);
console.log("It was fun sharing these facts with you. Goodbye! - (botName) from (botLocation).");